export const PROCESS_LABELS = [
  'Initializing',
  'Analyzing',
  'Thinking',
  'Finding Out',
  'Cooking',
  'Boiling',
  'Baking',
  'Plotting',
  'Daydreaming',
  'Brainstorming',
  'Overthinking',
  'Vibing',
  'Cooking Up Something Weird',
  'Chef Mode Activated',
  'Throwing Spaghetti at the Wall',
  'Summoning the Knowledge Gremlins',
  'Doing the Brain Dance',
  'Consulting the Magic 8-Ball',
  'Asking to Prabowo',
  'Asking to Gibran',
  'Calling Luhut for help',
];
